user_list:
  path: /users
  controller: App\Controller\UserController::getAll
  methods: [ GET ]

user_get:
  path: /users/{id}
  controller: App\Controller\UserController::getOne
  methods: [ GET ]

user_create:
  path: /users
  controller: App\Controller\UserController::create
  methods: [ POST ]

user_update:
  path: /users/{id}
  controller: App\Controller\UserController::update
  methods: [ PUT ]

user_delete:
  path: /users/{id}
  controller: App\Controller\UserController::delete
  methods: [ DELETE ]
